# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67f14729c33f975986d63ea155eae391e22015f385e18d0e903d205b246d47a23421174a0d4f94ff3efcdbb5552835024f77191ea8e789dbe357027e196e29d1

test:
  secret_key_base: 0416e6615d7fc5fcf40e43c1008c8928e54bd8bb7c21f9adf2dc7076ff090bb777f3609b8e84c4723aaab4332470cb74c01bf60c4be97d6e457b75187c5b2866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
